README.md
requirements.txt
setup.py

Ansible `2.2.1.0` has some security issues. Upgrading it as advised by the  security vulnerability scanner.

[FIX] Upgrade ansible requirement

---

requirements.txt

https://github.com/adobe/ops-cli/issues/6

Update boto3 and awscli

---

Dockerfile
Dockerfile.centos7.brew
README.md
examples/aws-kubernetes/README.md
examples/aws-kubernetes/compositions/generic/helm/provider_helm.tf.jinja2
examples/aws-kubernetes/update.sh

Publish docker image with ops-cli

---

src/ops/ansible/filter_plugins/commonfilters.py

Add escape_json filter

---

.travis.yml
build_scripts/Dockerfile
build_scripts/freeze_requirements.sh
build_scripts/run_tests.sh
requirements.txt
src/ops/__init__.py
src/ops/ansible/vars_plugins/clusterconfig.py
src/ops/ansible/vars_plugins/opsconfig.py
src/ops/cli/config.py
src/ops/cli/playbook.py
src/ops/inventory/ec2inventory.py
src/ops/inventory/generator.py
src/ops/jinja/__init__.py
tests/e2e/test_inventory.py
tests/e2e/test_jinja_filters.py
tests/e2e/test_playbook.py
tests/e2e/test_ssh.py

Upgrade to ansible 2.7

---

README.md
RELEASE.md

[DOCS] - Extract release instruction to RELEASE.md

---

build_scripts/Dockerfile
build_scripts/patches/kube_config.py
requirements.txt

These can be used in other task automation
in ops docker container
When using `ops` docker image, other task can be automated.
We are using internally azure-cli to interact with Azure envs,
kubernetes to intereact with k8s cluster and hvac for vault.

[BUILD] - Install azure-cli, kubernetes and vault python lib in docker image

---

src/ops/cli/helmfile.py

Generate kube config in order to avoid running helmfile on the wrong cluster.

Fix helmfile running on wrong cluster

---

.travis.yml

⚙️ adding pypi creds to travis

---

README.md
examples/aws-kubernetes/README.md
examples/cassandra-stress/README.md

Fixed a few typos in markdowns

Fixed typos in docs

---

setup.py
src/ops/cli/terraform.py
src/ops/data/terraform/terraformrc
src/ops/opsconfig.py

Enable plugin caching when running terraform commands

---

src/ops/cli/helmfile.py

Fixes #78
Removed hardcoded filters for helmfile composition
Added excluded keys for helmfile composition

Helmfile generated config shouldn't use hardcoded filters

---

src/ops/inventory/ec2inventory.py
src/ops/main.py

-Grouping import statements according to PEP 8
-Using the object itself rather than `len()` in boolean statements according to PEP 8
-Triple double quotes as opposed to triple single quotes according to PEP 257
-Combine print statement into `sys.exit()`
-Remove some unnecessary else statements
#73 
It makes the code much cleaner and easier to maintain. I am making small changes rather than a big ones that require a lot of review.
I used tests attached in tests\ directory.

Code is more PEP8-capable and PEP257-capable

---

README.md

Added docker version and download badges

Added docker badges

---

src/ops/cli/helmfile.py

minor key change to reflect changes in helm.global.aws map

minor key change to reflect changes in helm.global.aws map

---

examples/aws-kubernetes/clusters/my-kubernetes-cluster.yaml
examples/aws-kubernetes/compositions/generic/aws-eks/eks-cluster.tf.jinja2
examples/aws-kubernetes/compositions/generic/common/common_variables.tf.jinja2
examples/aws-kubernetes/compositions/generic/helm/dashboard.tf

Partly fixes https://github.com/adobe/ops-cli/issues/97

Switch to more inclusive language

---

src/ops/git_utils.py

@Asjidkalam (https://huntr.dev/users/Asjidkalam) has fixed a potential Arbitrary Code Execution vulnerability in your repository 🔨. For more information, visit our website (https://huntr.dev/) or click the bounty URL below...
Q | A
Version Affected | *
Bug Fix | YES
Original Pull Request | https://github.com/418sec/ops-cli/pull/1
Vulnerability README | https://github.com/418sec/huntr/blob/master/bounties/pip/ops-cli/1/README.md
Insecure YAML desearilization
`ops-cli` is a wrapper for Terraform, Ansible, Helmfile and SSH for cloud automation , which is vulnerable to Arbitary Code Execution.
Vulnerable to YAML deserialization attack caused by unsafe loading.
`python3 exp.py`
```python3
import os
#os.system('pip install --upgrade ops-cli')
from ops import git_utils
exploit = …
```

Security Fix for Arbitrary Code Execution - huntr.dev

---

src/ops/cli/config.py

Fix missing context cliargs

---

requirements.txt

Updated upstream dependencies, simpledi, to support python 3.11.

Bump dependencies for python 3.11 support

---

src/ops/cli/aws.py

Fix potential RCE vulnerability

Fix potential RCE vulnerability

---

README.md
src/ops/simplevault.py

Add okta MFA support for vault auth

Add okta MFA support for vault auth

---

src/ops/terraform/terraform_cmd_generator.py

Fix running terraform version 1.x

Fix running terraform version 1.x

---

src/ops/cli/ssh.py
tests/e2e/test_inventory.py
tests/e2e/test_ssh.py

Add ssh-dest-user ssh param so we can have a different user when using a jump host, especially useful for troubleshooting in case ldap is not working

Add ssh-dest-user ssh param
