README.md, setup.py, src/ops/data/ansible/tasks/remove_prometheus_alert_rules.yml
https://github.com/adobe/ops-cli/issues/8
=> Add possibility to skip Prometheus reload step in remove_prometheus_alert_rules.yml

src/ops/cli/terraform.py
Useful for cases where the tf states are stored remotely (ie. in an S3 bucket) with DynamoDB locking. If something happens (eg. credentials expire, terraform crashes), it would be useful to have a way to remove the lock that was acquired. Currently, this can only be done manually, by going to DynamoDB and removing the entry (the lock). However, terraform has a command to remove it. 
This PR makes it possible to run:
```sh
ops clusters/mycluster.yaml terraform force-unlock c462b73c-9df7-5901-d84f-6c384d854fce
ops clusters/mycluster.yaml terraform state push errored.tfstate
```
Fixes #10
=> Support ops terraform force-unlock

README.md, requirements.txt
This is the fix for https://github.com/adobe/ops-cli/issues/17
=> [FIX] Can't install ops-cli in dev mode on a fresh python virtualenv

src/ops/cli/config.py, src/ops/cli/terraform.py, src/ops/inventory/plugin/skms.py, src/ops/opsconfig.py
This PR contains a security fix which involves the usage of `yaml.safe_load()` function instead of `yaml.load()` (CVE-2017-18342 )
The second commit initialise `remove_local_cache` which is not set in case ops config file is not found.
=> Security update + fix for ops config

.travis.yml, Dockerfile, README.md, requirements.txt, setup.py, src/ops/cli/ssh.py, src/ops/cli/sync.py, src/ops/inventory/ec2inventory.py
Extend ssh and sync commands to allow custom hostnames/IPs
When using `ssh` and `sync` command with hosts/ips not in inventory, ops should fallback to 
provided hostname/ip when device is not found in inventory
E.g:
`ops cluster.yaml ssh 10.0.0.1` 
ssh into `bastion--10.0.0.1` even when the ip is not part of the inventory
`ops cluster.yaml sync file.txt 10.0.0.1:/tmp`
rsync into `bastion--10.0.0.1:/tmp`
This is needed in environments where the hosts are not part of the inventory
but reachable via bastion
Using local environment
N/A
=> Allow ssh'ing into custom hostnames/IPs not in inventory

.bumpversion.cfg, README.md
Release management: use bump2version to manage the version in all files.
Updated the README.md#Release with new instructions
=> [BUILD] - Use bump2version to manage version bump and release

src/ops/cli/terraform.py
-module-depth flag has been removed from terraform generated command as this is not supported anymore by latest version of terraform (0.12)
Related issue - https://github.com/adobe/ops-cli/issues/31 
It is required in order to be able to execute code with terraform 0.12 
Tested by running ops terraform plan & apply with terraform 0.11 and 0.12
=> removed -module-depth to support terraform 0.12

build_scripts/Dockerfile
Travis receives some rate limit errors from GitHub when trying to install the Helm plugins
=> [FIX] Fix dockerfile

requirements.txt, src/ops/ansible/filter_plugins/commonfilters.py, src/ops/simplevault.py
Upgrade the Vault code to use the new engine kv 2, which also uses namespaces. Accordingly, updating the Vault Python sdk hvac to a more modern version.
- upgrade hvac module to >0.9.x
- modify Vault code to work with the new kv engine.
- slight styling changes because some lines were just too long. Wish we had some PEP8 or linting enforced.
The old Vault engine has been changed within Adobe Audience Manager.
Built an ops docker image from my fork & branch, tested against CNS infrastructure that was using read_vault()
=> Upgrade Vault hvac and update Vault modules

build_scripts/build_package.sh, requirements.txt, src/ops/__init__.py
=> Make it possible to specify the current dir when using the Executor

src/ops/cli/inventory.py, src/ops/cli/sync.py
=> [FIX] Fix ansible get_vars calls in sync and inventory

src/ops/terraform/terraform_cmd_generator.py
Fixes https://github.com/adobe/ops-cli/issues/52
=> [FIX] Honor terraform.remove_local_cache flag

src/ops/ansible/filter_plugins/commonfilters.py, src/ops/cli/terraform.py, src/ops/simplevault.py
Enhance Vault modules and add support for enforcing a minimum ops version in Terraform clusters.
Addresses issue https://github.com/adobe/ops-cli/issues/55 
1. Enhance Vault module, now it will not muffle Exceptions and exposed another function called check_vault() that will return a Jinja2 friendly boolean ("true" or "false")
2. Added support for enforcing a minimum ops version in Terraform clusters ("ops_min_version")
1. Aims to solve scenarios where reading a non-existent Vault secret always returned "None" and never threw an exception.
2. Aims to make it easier to enforce a minimum version of ops across larger teams.
Built the ops Docker container locally from sources, ran Terraform plan and apply on our clusters.
Also tested with older versions of ops which now fail because another …
=> Enchance Vault utils

requirements.txt
Latest `himl` version fixes warning:
```
site-packages/himl/config_generator.py:183: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
```
=> Upgrade himl pip dependency

src/ops/inventory/azurerm.py
Moved python env shebang to first line because it only works if first line.
=> Moved python env shebang to first line

build_scripts/Dockerfile
Change `ops` user shell to `zsh` in docker image
=> Use zsh shell for ops user in docker image

src/ops/inventory/plugin/azr.py
Adds a parameter for the bastion tag in the azure plugin.
#14 
Allow customization in the cluster config.
I haven't run the tests for I'm not familiar with the test suite. How can I run the tests?
Should I create new tests for this feature?
=> Add bastion tag parameter to azure plugin

src/ops/opsconfig.py
`parts = os.path.realpath(config_path).split('/')` and `dir_name = '/'.join(parts)` are two expensive operations that undo each other's work. `rpartition()` is the better solution that avoids the use of the two aforementioned operations.
#73 (Best practices)
Code should be as fast as possible especially if there is zero cost in readability and maintainability.
I used tests attached in tests\ directory.
=> Replace expensive string concatenation and split with rpartition()

src/ops/cli/config_generator.py, src/ops/cli/helmfile.py, src/ops/cli/inventory.py, src/ops/cli/packer.py, src/ops/cli/parser.py, src/ops/cli/playbook.py, src/ops/cli/run.py, src/ops/cli/ssh.py, src/ops/cli/sync.py, src/ops/cli/terraform.py, src/ops/main.py
Add support for helmfile execution with `--concurrency` option
Fixes #80 
Running multiple helmfile release tillerless can cause concurrency issues.
https://github.com/roboll/helmfile/issues/690 
Usage: `ops data/env=dev/region=va6/project=ee/cluster=experiments/composition=helmfiles helmfile --concurrency=1 sync -- --selector chart=nginx-controller`
=> Add concurrency option for helmfile commands

src/ops/cli/helmfile.py
Removed default context fallback.  
Running directly against default kubernetes configured context has proven to be dangerous.
behaviour has improve after https://github.com/adobe/ops-cli/issues/84 was closed but after internal discusions it has been decided to remove running agains default kubernetes context altogether.  
Running against non eks clusters will be added in the future by adding in ops the possibility to explicitly specify the context (https://github.com/adobe/ops-cli/issues/89).
=> Removed default context fallback

README.md, examples/cassandra-stress/ansible/templates/cassandra_defaults.yaml, examples/cassandra-stress/ansible/templates/cassandra_defaults_12.yaml, examples/features/ansible-vault/README.md, examples/features/inventory/README.md, src/ops/cli/aws.py, src/ops/cli/packer.py, src/ops/cli/run.py, src/ops/inventory/SKMS.py, src/ops/inventory/generator.py, src/ops/inventory/plugin/skms.py, src/ops/simplevault.py, src/ops/terraform/terraform_cmd_generator.py
Fix some spelling errors. This is IMHO a purely cosmetic/non-functional change.
argumetns -> arguments (2x)
assumming -> assuming (1x)
coresponds -> corresponds (1x)
exaust -> exhaust (1x)
for for -> for (1x)
interpretted -> interpreted (1x)
overriden -> overridden (1x)
playbboks -> playbooks (1x)
primrary -> primary (1x)
refesh -> refresh (1x)
reponse -> response (1x)
technicial -> technical (1x)
varaiables -> variables (1x)
withing -> within (1x)
I've identified two other typos - but since fixing these would introduce a functional change, I *did not* touch them:
./src/ops/cli/aws.py:14 `def acess_key(profile):` (acess_key -> access_key)
./src/ops/simplevault.py:228 `except ImportErrori as e:` (ImportErrori -> ImportError)
n/a
Spelling errors are not nice...
Non-functional change, mostly …
=> Fix some spelling errors.

README.md, src/ops/cli/config.py, src/ops/cli/ssh.py, src/ops/inventory/sshconfig.py, tests/e2e/fixture/ansible/playbooks/play_module.yaml, tests/e2e/test_playbook.py
Ansible cli extra_vars (-e var=value) were not actually used due to some caching issues
Updated the tests with specific case which was not covered before
=> Fix missing ansible cli extra_vars
